branch-defaults:
  default:
    environment: Udagramng-env
environment-defaults:
  Udagramng-env:
    branch: null
    repository: null

deploy:
  artifact: www/Archive.zip
  
global:
  application_name: udagram-ng
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
