version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, elb, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  build_test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install dependencies in both apps
      - run:
          name: Frontend install
          command: |
            npm run frontend:install
      - run:
          name: Backend install
          command: |
            npm run backend:install
      # Build both frontend and backend
      - run:
          name: Frontend Build
          command: |
            npm run frontend:build

      - run:
          name: Backend Build
          command: |
            npm run backend:build

      # Run test on frontend
      - run:
          name: Test Frontend
          command: |
            npm run test:frontend


