version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
jobs:
  stage:
      - run:
          name: Test that this works
          command: |
            echo Hello Stage

  deploy:
      - run:
          name: Test that this works
          command: |
            echo Hello Deploy

workflows:
  stage_deploy:
    jobs:
      - stage
      - deploy:
          requires:
            - stage
